// Generated by CoffeeScript 1.10.0
(function() {
  var UnitConverter;

  UnitConverter = require('./lib/UnitConverter');

  module.exports = function(value, systemName) {
    return new UnitConverter(value, systemName);
  };

}).call(this);
