// Generated by CoffeeScript 1.10.0
(function() {
  var UnitParser;

  UnitParser = require('./lib/UnitParser');

  module.exports = function(value, systemName) {
    return new UnitParser(value, systemName);
  };

}).call(this);
