module.exports = {
  name:'byte',
  baseUnit:'b',
  units:{
    'b':{ratio:1},
    'B':{ratio:8},
    'kb':{ratio:Math.pow(2,10)},
    'kB':{ratio:Math.pow(2,10)*8},
    'mb':{ratio:Math.pow(2,20)},
    'MB':{ratio:Math.pow(2,20)*8},
    'gb':{ratio:Math.pow(2,30)},
    'gB':{ratio:Math.pow(2,30)*8},
    'tb':{ratio:Math.pow(2,40)},
    'tB':{ratio:Math.pow(2,40)*8}
  },
  aliases:{
    'Kb':'kb',
    'KB':'kB',
    'Mb':'mb',
    'MB':'mB',
    'Gb':'gb',
    'GB':'gB',
    'Tb':'tb',
    'TB':'tB'
  }
}